import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema } from '../registry';

/**
 * Button-specific property definitions
 */
const buttonProperties: PropertyMetadata[] = [
  {
    id: 'text',
    label: 'Text',
    type: 'expression',
    defaultValue: 'Click Me',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button text content',
    placeholder: 'e.g. Submit',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: '#4f46e5',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button background color',
  },
  {
    id: 'textColor',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#FFFFFF',
    supportsExpression: true,
    group: 'Styling',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.BUTTON],
    tooltip: 'Button text color',
  },
  {
    id: 'actionType',
    label: 'Action Type',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.BUTTON],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Show Alert' },
      { value: 'updateData', label: 'Update Data Store' },
      { value: 'updateVariable', label: 'Update Variable' },
      { value: 'executeCode', label: 'Execute Code' },
      { value: 'createRecord', label: 'Create Record' },
      { value: 'updateRecord', label: 'Update Record' },
      { value: 'deleteRecord', label: 'Delete Record' },
      { value: 'selectRecord', label: 'Select Record' },
      { value: 'navigate', label: 'Navigate' },
    ],
    tooltip: 'Action to perform when button is clicked',
  },
  {
    id: 'actionAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'alert',
    tooltip: 'Message to display in alert',
    placeholder: 'e.g. Hello World!',
  },
  {
    id: 'actionUpdateKey',
    label: 'Data Store Key',
    type: 'string',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateData',
    tooltip: 'Key in dataStore to update',
    placeholder: 'e.g. user.name',
  },
  {
    id: 'actionUpdateValue',
    label: 'Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateData',
    tooltip: 'Value to set in dataStore',
    placeholder: 'e.g. {{inputName.value}}',
  },
  {
    id: 'actionVariableName',
    label: 'Variable Name',
    type: 'string',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 4,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateVariable',
    tooltip: 'Name of variable to update',
    placeholder: 'e.g. counter',
  },
  {
    id: 'actionVariableValue',
    label: 'Variable Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 5,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'updateVariable',
    tooltip: 'Value to set for variable',
    placeholder: 'e.g. {{counter + 1}}',
  },
  {
    id: 'actionCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 6,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'executeCode',
    tooltip: 'JavaScript code to execute',
    placeholder: 'e.g. console.log("Hello")',
  },
  {
    id: 'dataSourceName',
    label: 'Data Source',
    type: 'string',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 7,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => {
      const actionType = (props as any).actionType;
      return actionType === 'createRecord' || actionType === 'updateRecord' || actionType === 'deleteRecord' || actionType === 'selectRecord';
    },
    tooltip: 'Data source name',
    placeholder: 'e.g. users',
  },
  {
    id: 'newRecordData',
    label: 'New Record Object',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 8,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'createRecord',
    tooltip: 'JSON object for new record',
    placeholder: 'e.g. {{ { name: inputName.value } }}',
  },
  {
    id: 'actionNavigatePageId',
    label: 'Page ID',
    type: 'string',
    defaultValue: '',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 9,
    applicableTo: [ComponentType.BUTTON],
    visibleIf: (props) => (props as any).actionType === 'navigate',
    tooltip: 'Page ID to navigate to',
    placeholder: 'e.g. page-2',
  },
];

/**
 * Button-specific groups
 * Order values use DEFAULT_GROUP_ORDER from registry for consistency
 */
const buttonGroups: PropertyGroup[] = [
  { id: 'Events', label: 'Events', tab: 'Events', collapsible: true, defaultCollapsed: false },
];

/**
 * Button property schema
 */
export const buttonSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.BUTTON,
  buttonProperties,
  commonTabs,
  [...commonGroups, ...buttonGroups]
);

