import { ComponentType } from '../../../types';
import { ComponentPropertySchema, PropertyMetadata, PropertyGroup, PropertyTab } from '../metadata';
import { commonProperties, commonTabs, commonGroups, createPropertySchema, DEFAULT_GROUP_ORDER } from '../registry';
import { EventsGroupRenderer } from './input-events-renderer';

/**
 * Textarea-specific property definitions
 */
const textareaProperties: PropertyMetadata[] = [
  // General Tab - Value and Basic Properties
  {
    id: 'value',
    label: 'Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Current value of the textarea (supports expressions).',
    placeholder: 'e.g. {{user.message}} or "Hello"',
  },
  {
    id: 'defaultValue',
    label: 'Default Value',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Default value for the textarea field',
    placeholder: 'e.g. {{user.message}} or "Hello"',
  },
  {
    id: 'placeholder',
    label: 'Placeholder',
    type: 'expression',
    defaultValue: 'Enter long text...',
    supportsExpression: true,
    group: 'Basic',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Placeholder text shown when textarea is empty',
    placeholder: 'e.g. Enter your message...',
  },
  
  // Validation properties moved to General tab
  {
    id: 'required',
    label: 'Required',
    type: 'expression',
    defaultValue: false,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Whether the textarea is required',
    placeholder: 'e.g. true or {{someCondition}}',
  },
  {
    id: 'min',
    label: 'Min Value',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 1,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Minimum value (supports expressions)',
    placeholder: 'e.g. 0 or {{minValue}}',
  },
  {
    id: 'max',
    label: 'Max Value',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 2,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Maximum value (supports expressions)',
    placeholder: 'e.g. 100 or {{maxValue}}',
  },
  {
    id: 'step',
    label: 'Step',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 3,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Step value',
    placeholder: 'e.g. 1 or 0.1',
  },
  {
    id: 'pattern',
    label: 'Regex Pattern',
    type: 'string',
    defaultValue: '',
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 4,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Regular expression pattern for validation',
    placeholder: 'e.g. [A-Za-z]+',
  },
  {
    id: 'maxLength',
    label: 'Max Length',
    type: 'number',
    defaultValue: 0,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 5,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Maximum number of characters allowed',
  },
  {
    id: 'errorMessage',
    label: 'Error Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Validation',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 2,
    propertyOrder: 6,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Custom error message shown when validation fails',
    placeholder: 'e.g. "Please enter a valid value" or {{customError}}',
  },
  
  // Layout properties - use common properties (x, y, width, height from commonProperties)
  // Only add zIndex as a custom property in General tab Layout group
  {
    id: 'zIndex',
    label: 'Z-Index',
    type: 'expression',
    defaultValue: undefined,
    supportsExpression: true,
    group: 'Layout',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 1,
    propertyOrder: 4,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Z-index for layering components (supports expressions)',
    placeholder: 'e.g. 1, 10, 100 or {{zIndex}}',
  },
  
  // Styles Tab - Typography
  {
    id: 'fontSize',
    label: 'Font Size',
    type: 'expression',
    defaultValue: 14,
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Font size in pixels',
    placeholder: 'e.g. 14 or {{theme.fontSize}}',
  },
  {
    id: 'fontFamily',
    label: 'Font Family',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Font family name',
    placeholder: 'e.g. Arial, sans-serif',
  },
  {
    id: 'fontWeight',
    label: 'Font Weight',
    type: 'dropdown',
    defaultValue: 'normal',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'normal', label: 'Normal' },
      { value: 'bold', label: 'Bold' },
      { value: '100', label: '100' },
      { value: '200', label: '200' },
      { value: '300', label: '300' },
      { value: '400', label: '400' },
      { value: '500', label: '500' },
      { value: '600', label: '600' },
      { value: '700', label: '700' },
      { value: '800', label: '800' },
      { value: '900', label: '900' },
    ],
    tooltip: 'Font weight',
  },
  {
    id: 'fontStyle',
    label: 'Font Style',
    type: 'dropdown',
    defaultValue: 'normal',
    group: 'Typography',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 0,
    propertyOrder: 3,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'normal', label: 'Normal' },
      { value: 'italic', label: 'Italic' },
    ],
    tooltip: 'Font style',
  },
  {
    id: 'color',
    label: 'Text Color',
    type: 'color',
    defaultValue: '#111827',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Text color',
  },
  {
    id: 'backgroundColor',
    label: 'Background Color',
    type: 'color',
    defaultValue: '#ffffff',
    supportsExpression: true,
    group: 'Color',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 1,
    propertyOrder: 1,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Background color',
  },
  
  // Advanced properties moved to Styles tab
  {
    id: 'className',
    label: 'Custom Class',
    type: 'string',
    defaultValue: '',
    group: 'Advanced',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 2,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Custom CSS class names',
    placeholder: 'e.g. my-custom-class',
  },
  {
    id: 'customAttributes',
    label: 'Custom Attributes',
    type: 'json',
    defaultValue: '',
    group: 'Advanced',
    tab: 'Styles',
    tabOrder: 1,
    groupOrder: 2,
    propertyOrder: 1,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'Custom HTML attributes as JSON (e.g., {"data-testid": "my-textarea"})',
    placeholder: '{"data-testid": "my-textarea"}',
  },
  
  // Events Tab
  {
    id: 'onChangeActionType',
    label: 'On Change Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when textarea value changes',
  },
  {
    id: 'onChangeAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 1,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onChangeActionType === 'alert',
    tooltip: 'Message to display in alert (supports expressions)',
    placeholder: 'e.g., {{ "Value changed: " + event.target.value }}',
  },
  {
    id: 'onChangeCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 2,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onChangeActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when textarea value changes',
    placeholder: 'e.g., {{ (() => { console.log(event.target.value); })() }}',
  },
  // On Focus Action
  {
    id: 'onFocusActionType',
    label: 'On Focus Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 10,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when textarea gains focus',
  },
  {
    id: 'onFocusAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 11,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onFocusActionType === 'alert',
    tooltip: 'Message to display in alert when textarea gains focus (supports expressions)',
    placeholder: 'e.g., {{ "Textarea focused" }}',
  },
  {
    id: 'onFocusCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 12,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onFocusActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when textarea gains focus',
    placeholder: 'e.g., {{ (() => { console.log("Focused"); })() }}',
  },
  // On Blur Action
  {
    id: 'onBlurActionType',
    label: 'On Blur Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 20,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when textarea loses focus',
  },
  {
    id: 'onBlurAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 21,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onBlurActionType === 'alert',
    tooltip: 'Message to display in alert when textarea loses focus (supports expressions)',
    placeholder: 'e.g., {{ "Textarea blurred" }}',
  },
  {
    id: 'onBlurCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 22,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onBlurActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when textarea loses focus',
    placeholder: 'e.g., {{ (() => { console.log("Blurred"); })() }}',
  },
  // On Enter Key Press Action
  {
    id: 'onEnterActionType',
    label: 'On Enter Action',
    type: 'dropdown',
    defaultValue: 'none',
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 30,
    applicableTo: [ComponentType.TEXTAREA],
    options: [
      { value: 'none', label: 'None' },
      { value: 'alert', label: 'Alert' },
      { value: 'executeCode', label: 'Execute Code' },
    ],
    tooltip: 'Action to perform when Enter key is pressed',
  },
  {
    id: 'onEnterAlertMessage',
    label: 'Alert Message',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 31,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onEnterActionType === 'alert',
    tooltip: 'Message to display in alert when Enter key is pressed (supports expressions)',
    placeholder: 'e.g., {{ "Enter key pressed" }}',
  },
  {
    id: 'onEnterCodeToExecute',
    label: 'Code to Execute',
    type: 'expression',
    defaultValue: '',
    supportsExpression: true,
    group: 'Events',
    tab: 'Events',
    tabOrder: 2,
    groupOrder: 0,
    propertyOrder: 32,
    applicableTo: [ComponentType.TEXTAREA],
    visibleIf: (props) => (props as any).onEnterActionType === 'executeCode',
    tooltip: 'JavaScript code to execute when Enter key is pressed',
    placeholder: 'e.g., {{ (() => { console.log("Enter pressed"); })() }}',
  },
  
  // Accessibility
  {
    id: 'accessibilityLabel',
    label: 'Accessibility Label',
    type: 'string',
    defaultValue: 'Text area for long text',
    group: 'Accessibility',
    tab: 'General',
    tabOrder: 0,
    groupOrder: 3,
    propertyOrder: 0,
    applicableTo: [ComponentType.TEXTAREA],
    tooltip: 'A descriptive label for screen readers',
    placeholder: 'A descriptive label for screen readers',
  },
];

/**
 * Textarea-specific tabs - only General, Styles, and Events
 */
const textareaTabs: PropertyTab[] = [
  { id: 'General', label: 'General', order: 0 },
  { id: 'Styles', label: 'Styles', order: 1 },
  { id: 'Events', label: 'Events', order: 2 },
];


/**
 * Textarea-specific groups
 */
const textareaGroups: PropertyGroup[] = [
  { 
    id: 'Basic', 
    label: 'Basic', 
    tab: 'General', 
    order: DEFAULT_GROUP_ORDER['Basic'], 
    collapsible: true, 
    defaultCollapsed: false 
  },
  { id: 'Validation', label: 'Validation', tab: 'General', collapsible: true, defaultCollapsed: false },
  { id: 'Typography', label: 'Typography', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { id: 'Color', label: 'Color', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { 
    id: 'Events', 
    label: 'Events', 
    tab: 'Events', 
    collapsible: true, 
    defaultCollapsed: false,
    customGroupRenderer: EventsGroupRenderer,
  },
  { id: 'Advanced', label: 'Advanced', tab: 'Styles', collapsible: true, defaultCollapsed: false },
  { id: 'Accessibility', label: 'Accessibility', tab: 'General', collapsible: true, defaultCollapsed: false },
];

/**
 * Textarea property schema
 */
export const textareaSchema: ComponentPropertySchema = createPropertySchema(
  ComponentType.TEXTAREA,
  textareaProperties,
  textareaTabs,
  [...commonGroups, ...textareaGroups]
);
